name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.Js
        uses: actions/setup-node@v2
        with:
          node-version: 22.x
      - name: run install and build
        run: |
          npm install
          npm run build
