name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.Js
        uses: actions/setup-node@v2
        with:
          node-version: 22.x
      - name: run install and build
        run: |
          npm install
          npm run build
      - name: Deploy via FTP to Hostinger!
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{secrets.FTP_SERVER}}
          username: ${{secrets.FTP_USERNAME}}
          password: ${{secrets.FTP_PASSWORD}}
          port: 21
          protocol: ftp
          local-dir: ./dist/
          server-dir: /public_html/
